### ISSUE TITLE
WSC Connection failed with 113

### ISSUE THREAD

**Issue by hiflyer1992** [typester/esp32-websocket-client#1]
![Screenshot from 2019-04-26 14-12-31](https://user-images.githubusercontent.com/50013348/56795138-6ba05f00-682d-11e9-8adf-62d82acb63e9.png)

Hi Daisuke Murase 
Firstly Thanks for take time to develop ESP-WEB-Socket client. 
I ran TCP server code on another esp32. 
I got the following response.

**Comment by typester** [comment]
Hi,

Can you give me DEBUG level logs?

And also you might want to try updating this component. I did some modifications to solve some minor issue around websocket connection.

**Comment by typester** [comment]
I will close this issue. If you still have this issue, please reopen.
